authors:
  daveprowse:
    name: Dave Prowse
    description: Maintainer of Draw On Gnome.
    avatar: https://avatars.githubusercontent.com/u/65040686
    url: https://github.com/daveprowse/Draw-On-Gnome
    