name: Build and Test Extension

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint-check

    - name: Type check
      run: npm run type-check

    - name: Security audit
      run: npm audit --audit-level moderate

  build:
    needs: lint-and-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y glib2.0-dev gettext

    - name: Install npm dependencies
      run: npm ci

    - name: Build extension
      run: npm run build

    - name: Validate package structure
      run: |
        unzip -l build/draw-on-gnome@daveprowse.github.io.zip
        test -f build/draw-on-gnome@daveprowse.github.io/extension.js
        test -f build/draw-on-gnome@daveprowse.github.io/metadata.json
        test -f build/draw-on-gnome@daveprowse.github.io/schemas/gschemas.compiled

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: draw-on-gnome-extension
        path: build/*.zip
        retention-days: 30

    - name: Upload to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/draw-on-gnome@daveprowse.github.io.zip
        asset_name: draw-on-gnome-extension.zip
        asset_content_type: application/zip
